import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Router from "next/router";
import { useEffect, useState } from "react";
import { Main } from "../components/main";
import { api } from "../services/api";

const Home: NextPage = () => {
  const [plan, setPlan] = useState('')
  const [planMax, setPlanMax] = useState(0)
  const [loading, setLoading] = useState(true);
  const onExit = () => {
    localStorage.clear();
    Router.replace("/login");
  };

  const loadUser = async () => {
    const response = await api.get("/user/details",{
      headers:{
        'Authorization': 'Bearer ' + localStorage.getItem('@token')
      }
    });
    if(!!response.data?.id){
      setPlan(response.data?.plan?.title)
      setPlanMax(response.data?.plan?.maxSong)
    }
   setLoading(false)
  };

  useEffect(()=>{
    if(typeof window !== undefined){
      loadUser()
    }
  },[typeof window]);


  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <span onClick={onExit} className="button-back-container">
        <img width={20} height={20} src={"/exit.png"} />
      </span>
      <main className="main-app">
        <Main plan={plan} planMax={planMax} />
      </main>
      <div style={{display: loading? 'flex': 'none'}} className={"loader"} />
    </div>
  );
};

export default Home;
